services:
  proxy-service:
    image: hellogrpc/proxy-service:latest
    ports:
      - "80:8080"
      - "443:443"
    depends_on:
      - prime-number-server
  prime-number-server:
    image: hellogrpc/prime-number-server:latest
