services:
  proxy-service:
    image: hellodixa/proxy-service:latest
    ports:
      - "80:8080"
      - "443:443"
    depends_on:
      - prime-number-server
    environment:
      - PRIMEGENERATOR_GRPC_HOST=prime-number-server
  prime-number-server:
    image: hellodixa/prime-number-server:latest
